# Generated by Django 3.1.1 on 2021-03-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('movie_file', models.FileField(upload_to='movies/movie_files')),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
